# Generated by Django 5.1.1 on 2024-10-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
