# Generated by Django 5.1.1 on 2024-10-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_alter_order_phone_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='town',
        ),
    ]
