# Generated by Django 5.1.1 on 2024-10-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0006_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_cart',
        ),
    ]
