# Generated by Django 5.1.1 on 2024-10-16 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_order_amount_paid_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
